server:
    port: 8080
    context-path: /

spring:
  datasource:
    driver: com.mysql.jdbc.driver
    url: jdbc:mysql://localhost:3306/liuhui
    username: liuhui
    password: liuhui0203
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  resources:
    static-locations: classpath:/resources/,classpath:/
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: false
    prefer-file-system-access: true
    suffix: .ftl
    prefix: templates/view/
    template-loader-path: classpath:/
    settings:
        template_update_delay: 0
        default_encoding: UTF-8
        classic_compatible: true
    order: 1


