server:
    port: 8080
    context-path: /

spring:
  datasource:
    driver: com.mysql.jdbc.driver
#    jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    url: jdbc:mysql://localhost:3306/liuhui
    username: liuhui
    password: liuhui0203
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  resources:
    static-locations: classpath:/resources/,classpath:/
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: false
    prefer-file-system-access: true
    suffix: .ftl
    prefix: templates/view/
    template-loader-path: classpath:/
    settings:
        template_update_delay: 0
        default_encoding: UTF-8
        classic_compatible: true
    order: 1
  output:
    ansi:
      enabled: detect
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 500
#logging:
#  file: weblog.log

